import Head from "next/head";
import Image from "next/image";
import { Plus_Jakarta_Sans } from "@next/font/google";
const pjsfont = Plus_Jakarta_Sans({ subsets: ["latin"] });

import { postData } from "@/utils";
import axios from "axios";
import { useState } from "react";

export default function Home() {
  const [url, seturl] = useState("");
  const [shortUrl, setShorturl] = useState("");
  const [error, setError] = useState("");

  const handleClick = async (e) => {
    try {
      const res = await postData("/api/v1/url/create", {
        originalUrl: `${url}`,
      });
      setShorturl(res.data.result.shortUrl);
      setError("");
    } catch (error) {
      setError(error.response?.data?.error);
      setShorturl("");
    }
    e.preventDefault();
  };

  return (
    <>
      <Head>
        <title>Url Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${pjsfont.className} selection:bg-red-400 selection:text-white`}
      >
        <header>
          <div className="mt-20">
            <h1 className="text-center text-4xl font-extrabold text-redGuy">
              Make your URL Shorter !
            </h1>
            <p className="mx-auto mt-1 text-center font-light">
              TrollLink is a random link personalization tool that enable to
              make your life easier.
            </p>
          </div>
          <div className="mx-auto mt-14 w-6/12 overflow-hidden rounded-lg border-2 border-redGuy px-4 py-4">
            <div className="flex justify-between gap-4">
              <input
                className="w-full focus:outline-none"
                type="text"
                placeholder="Paste a link to shorten it"
                onChange={(e) => {
                  seturl(e.target.value);
                }}
              />
              <button
                className="px rounded-lg bg-redGuy px-4 py-2 font-light text-white"
                onClick={handleClick}
              >
                Shorten
              </button>
            </div>
          </div>
          {shortUrl} {error}
        </header>
      </main>
    </>
  );
}
