import Head from "next/head";
import { useEffect, useState } from "react";

import { fetchData, postData } from "@/utils";
import Layout from "@/components/Layout";
import ClipboardCopy from "@/components/ClipboardCopy";
import Footer from "@/components/Footer";
import OpenNewTab from "@/components/OpenNewTab";
import { Toaster, toast } from "react-hot-toast";

export default function Home({ username }) {
  const [url, seturl] = useState("");
  const [shortUrl, setShortUrl] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [user, setUser] = useState(false);

  useEffect(() => {
    setUser(true);
    toast.success(`Signed in as ${username}!`);

    // Give the user a chance to read the toast
    setTimeout(() => {
      toast.dismiss();
    }, 5000);

    // console.log("trigger");
  }, [username]);

  const handleClick = async (e) => {
    setLoading(true);
    setError("");
    setShortUrl("");

    const result = await postData("/api/v1/url/create", {
      originalUrl: `${url}`,
    });

    if (result?.data) {
      setTimeout(() => {
        setShortUrl(
          `${process.env.NEXT_PUBLIC_BASE_URL}/${result.data.result.urlId}`
        );
        setLoading(false);
      }, 5000);
    } else {
      setTimeout(() => {
        setError(result.response?.data?.message || "Something went wrong");
        setLoading(false);
      }, 3000);
    }

    e.preventDefault();
  };

  return (
    <>
      <Head>
        <title>TrollLink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <header>
            {user && (
              <Toaster
                toastOptions={{
                  duration: 2000,
                }}
              />
            )}
            <div className="mt-20">
              <h1 className="text-4xl font-extrabold text-center text-redGuy">
                Make your URL Shorter !
              </h1>
              <p className="mx-auto mt-1 font-light text-center">
                TrollLink is a random link personalization tool that enable to
                make your life more troll.
              </p>
            </div>
            <div className="w-full px-4 py-4 mx-auto overflow-hidden mt-14 md:w-6/12 md:py-2">
              <div className="flex flex-col justify-between gap-4 md:flex-row">
                <input
                  className="w-full bg-transparent focus:border:white focus:border-b focus:border-redGuy focus:outline-none"
                  type="text"
                  placeholder="https://example.com"
                  onChange={(e) => {
                    seturl(e.target.value);
                  }}
                />
                <button
                  className={`px rounded-xl bg-redGuy px-4 py-4 font-light text-white shadow-sm shadow-red-200 backdrop-blur-md transition-all duration-300 ease-in-out hover:bg-red-700 ${
                    loading && "disabled cursor-not-allowed"
                  }`}
                  onClick={handleClick}
                  disabled={loading}
                >
                  Shorten
                </button>
              </div>
            </div>
            {/* Result */}
            <div className="mx-auto mt-10">
              {loading && (
                <div className="flex justify-center">
                  <span className="mx-auto loader"></span>
                </div>
              )}
              {shortUrl && (
                <>
                  <div className="w-full px-4 py-4 mx-auto overflow-hidden border-2 rounded-lg mt-14 border-redGuy md:w-6/12 md:py-2">
                    <div className="flex flex-row flex-wrap justify-between gap-2">
                      <p className="flex items-center select-all cursor-grab">
                        {shortUrl}
                      </p>
                      <div className="flex flex-row">
                        <ClipboardCopy text={shortUrl} targetUrl={shortUrl} />
                        <OpenNewTab targetUrl={shortUrl} />
                      </div>
                    </div>
                  </div>
                </>
              )}
              {error && (
                <div className="flex justify-center gap-4">
                  <p className="text-2xl font-extrabold text-center text-redGuy">
                    {error}
                  </p>
                </div>
              )}
            </div>
          </header>
          <Footer />
        </Layout>
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const fetch = await fetchData("/api/v1/user", context.req.cookies.token);
  const data = fetch.data.data.username;

  return {
    props: { username: data },
  };
}
